### ISSUE TITLE
typo in ConfShopware6ApiBase

### ISSUE THREAD

**Issue by rawdlite** [bitranox/lib_shopware6_api_base#1]
* **I'm submitting a ... **
  - [ x] bug report
  - [ ] feature request
  - [ ] support request

Heads up for this library. Greatly appreciated.
Just came across a typo in the ConfShopware6ApiBase Code.

Copied admin/settings/system/itegrations in my URL and was wondering why it was not working. ;-)

Needs to be '/admin#/sw/integration/index'

Guesss this is too trivial for a pull request.

cheers tom

**Comment by bitranox** [comment]
Dear Tom,
its a missunderstanding, not a typo - it should read : 

Web Adminitration Interface : settings --> system --> integration 

or directly via URL : 
"https://<fqdn>/admin#/sw/integration/index", were <fqdn> ist the fully qualified domain name like "https://myshop.mydomain.com/admin#/sw/integration/index"

I will clarify that in the documentation, thanks for the hint !

yours sincerely

bitranox

**Comment by rawdlite** [comment]
I guess its both then as it says 'itegrations'. 

cheers tom

**Comment by bitranox** [comment]
indeed !

bitranox

**Comment by rubberfashion** [comment]
Thanks a lot. Great work and great libary. Help a LOT! :)
