### ISSUE TITLE
Uploading a document

### ISSUE THREAD

**Issue by laf0rge** [bitranox/lib_shopware6_api_base#3]
I'm currently using this library to integrate my Odoo based ERP system with shopware.  So far, it is working great.

However, I'm now trying to figure out how I can upload the PDF invoices as shopware 'documents', and it seems it is not possible via this library:
* I don't see a way to override the Contet-Type that is sent in POST requests.  the _get_header() method always returns `application/json`.
* I don't see how I could post non-JSON data as the use of `json.dumps(payload)` is hard-coded in the _request() method

The REST API reference for this can be found at https://shopware.stoplight.io/docs/admin-api/b3A6MTMzMTcwNzM-upload-a-file-for-a-document

Do you have any thoughts how you'd want to support this feature? I would assume that a _base API_ module should ideally be flexible/generic enough to do anything the shopware6 API offers.

**Comment by bitranox** [comment]
IC. Should be easy to implement, let me look into it in the next few days ... 
thanks for the report !
yours sincerely
Robert

**Comment by laf0rge** [comment]
Thank you.

**Comment by laf0rge** [comment]
I found a third problem: To use this upload feature, you also need to pass along query parameters for the mandatory extension parameter (e.g. 'pdf'). 

There's currently no way (unless I missed it) how a higher-layer function/method can pass query parameters (requests.post `params` argument).

**Comment by bitranox** [comment]
diggah, check v2.0.8, should be done.
yours sincerely
Robert

**Comment by bitranox** [comment]
uh - ah - missed the parameters - sow it too late ...

**Comment by bitranox** [comment]
ok, check https://github.com/bitranox/lib_shopware6_api_base/releases/tag/v2.0.9
should be complete now.
let me know
yours sincerely
Robert
