### ISSUE TITLE
EqualsAnyFilter is not using "equalsAny" as default in type parameter.

### ISSUE THREAD

**Issue by PH89** [bitranox/lib_shopware6_api_base#5]
See: https://github.com/bitranox/lib_shopware6_api_base/blame/a207c9b345e864f028c87e0d7cd4b98311d21aea/lib_shopware6_api_base/lib_shopware6_api_base_criteria_filter.py#L148

This causes the EqualsAnyFilter to fail.

**Comment by bitranox** [comment]
thank you Patrik for pointing that out - I corrected that bug and made a new release.
It is solved in  https://github.com/bitranox/lib_shopware6_api_base/releases/tag/v2.1.4

**Comment by bitranox** [comment]
solved
